### ISSUE TITLE
Make arguments expectation an extension

### ISSUE THREAD

**Issue by h2oboi89** [ryanplusplus/mach.js#14]
Current:
- `mayBeCalled()`
- `shouldBeCalled()`
- `shouldBeCalledWith()`
- `shouldBeCalledWithAny()`

Proposed:
Bases:
- `mayBeCalled()`
- `shouldBeCalled()`

Extensions:
- `<base>.With()`
- `<base>.WithAny()`

**Comment by ryanplusplus** [comment]
All of the permutations for this are already available. Although it might simplify the implementation a bit, I think having slightly fewer `()`s littered about means the extra code is worth maintaining.
