### ISSUE TITLE
match function arguments

### ISSUE THREAD

**Issue by h2oboi89** [ryanplusplus/mach.js#21]
ability to match callback arguments in functions

**Comment by ryanplusplus** [comment]
How would this work? If you're checking for straight equality, doesn't that already work?

**Comment by ryanplusplus** [comment]
@h2oboi89 something like this?

``` javascript
f.shouldBeCalledWithAnyArguments().andWillInvokeArgumentWith(2, [1, 'a', {}]);
```

**Comment by h2oboi89** [comment]
Assuming `2` is position index into args and `[1, '1', {}]` is arguments for the callback:

I think we should default to using last argument for callback if position index is not specified, or maybe do some clever analysis of args and find first / last one that is a function. Then for things like promises and other cases where there are multiple callbacks we can specify which to call like you have.

**Comment by h2oboi89** [comment]
Superceded by #26
